package ch03;

public class A_Exception {

	public static void main(String[] args) {
		
		int number = 0;
		System.out.println(10 / number);
		
		System.out.println("나누기 연산이 실행됩니다.");
		
	}

}
